### ISSUE TITLE
[Chore] : version1.1 초기 세팅

### ISSUE THREAD

**Issue by arinming** [Mojacknong/Mojacknong_Android#120]
## ✏️ Description
version 1.1로 세팅을 초기화합니다

## To-Do List
- [x] 이미지 파일 삭제
- [x] 스크린 화면 삭제
- [x] 데이터 삭제
- [x] 패키지명 변경
- [x] Android 로그인 재설정
- [x] iOS 로그인 재설정 및 구글 로그인 추가
