### ISSUE TITLE
[Feat] : HomeScreen 채소 등록 UI 구현

### ISSUE THREAD

**Issue by arinming** [Mojacknong/Mojacknong_Android#129]
## ✏️ Description
채소 등록 UI 구현

## To-Do List
- [ ] 채소 등록하기 버튼으로 Navigation 구현
- [ ] 앱 바 구현
- [ ] 등록 채소 컴포넌트 구현
- [ ] 이전/다음 버튼 구현
- [ ] 채소 별명 입력 컴포넌트
- [ ] 달력 컴포넌트
- [ ] 등록 다이어로그 구현
