### ISSUE TITLE
[Feat] HomeVegeDeleteScreen UI 구현

### ISSUE THREAD

**Issue by arinming** [Mojacknong/Mojacknong_Android#137]
## To-Do List
- [ ] 앱 바 구현
- [ ] 삭제 이유 화면 구현
- [ ] 재배 성공 화면 구현
- [ ] 재배 실패 화면 구현

## ETC
루틴 추가 화면을 구현하려 하였으나 피그마 상 문서 진척도 보완필요 상태를 확인하여, 채소 삭제 스크린부터 구현합니다!
