### ISSUE TITLE
[Feat] Home 성장 일기 UI 구현

### ISSUE THREAD

**Issue by arinming** [Mojacknong/Mojacknong_Android#143]
## ✏️ Description
Home 화면에서 성장일기로 넘어갔을 때의 UI를 구현합니다.

## To-Do List
- [x] 채소 성장 일기 정보 컴포넌트 구현
- [x] 성장 일기 있을 때, 없을 때 구분
- [x] 일기 컴포넌트 구현
