### ISSUE TITLE
[Feat] 채소 정보 UI 구현

### ISSUE THREAD

**Issue by arinming** [Mojacknong/Mojacknong_Android#150]
## ✏️ Description
채소 정보를 눌렀을 때의 상세 view를 구현합니다.

## To-Do List
- [ ] 채소 정보 appBar
- [ ] 채소 정보 컴포넌트
- [ ] 채소 별명, 키우기 시작한 날
