### ISSUE TITLE
[Feat] 팜클럽 가입 UI

### ISSUE THREAD

**Issue by geonheey** [Mojacknong/Mojacknong_Android#164]
## ✏️ Description
탐색 탭에 있는 팜클럽 정보를 누르면 나타나는 팜클럽 가입 화면을 구현합니다.

## To-Do List
- [ ] 팜클럽 정보 UI
- [ ] 준비 사항 UI
- [ ] 팜클럽 가입 바텀시트
