### ISSUE TITLE
[Feat] 채소 삭제 API 연동

### ISSUE THREAD

**Issue by arinming** [Mojacknong/Mojacknong_Android#224]
## ✏️ Description
채소 삭제 API를 연동합니다.

## To-Do List
- [x] 1개의 채소만 선택 가능하도록 구현
- [x] 채소 삭제 API 연동
- [x] 채소 아예 없을 경우
- [ ] 팜클럽 가입한 채소인 경우
