### ISSUE TITLE
[Feat] 채소 히스토리 조회 관련 API 연동

### ISSUE THREAD

**Issue by geonheey** [Mojacknong/Mojacknong_Android#234]
## ✏️ Description
채소 히스토리 관련 API들을 연동을 합니다.

## To-Do List
- [x] 유저 히스토리 - 채소 연동
- [x] 채소 히스토리 단일 조회 연동
- [x] 채소 히스토리 목록 조회 연동
