### ISSUE TITLE
[Hotfix] 머지 충돌: 괄호 처리 오류

### ISSUE THREAD

**Issue by geonheey** [Mojacknong/Mojacknong_Android#254]
## ✏️ Description
머지 충돌 시, 괄호 처리 오류를 해결합니다.

## To-Do List
- [x] 괄호 처리 오류를 해결
- [x] 팜클럽 성공 화면 연결하기
- [x] 팜클럽 성공 화면 임시 뷰 만들기
