### ISSUE TITLE
[Feat] 미션 인증 목록 조회(유저) API 연동

### ISSUE THREAD

**Issue by geonheey** [Mojacknong/Mojacknong_Android#270]
## ✏️ Description
이전 스텝 로직 수정 & 미션 인증 목록 조회(유저) API 연동을 합니다.
즉, 필터링을 거쳐 유저별로 미션 인증 목록을 볼 수 있습니다.

## To-Do List
- [x] 이전 스텝 로직 수정
- [x] 미션 인증 목록 조회 API 연동
- [x] 유저 닉네임으로 필터링해서 미션 인증 목록 가져오기
