### ISSUE TITLE
[Feat] : 마이페이지, 커뮤니티, 로그인 페이지 UI 3차 수정

### ISSUE THREAD

**Issue by arinming** [Mojacknong/Mojacknong_Android#35]
## ✏️ Description
디자인 변경된 대로 UI를 수정합니다.

## To-Do List
- [x] 마이페이지 UI 수정
- [x] 커뮤니티 UI 수정
- [ ] 로그인 페이지 온보딩 추가
