### ISSUE TITLE
[Feat] : 마이페이지 UI 완성

### ISSUE THREAD

**Issue by arinming** [Mojacknong/Mojacknong_Android#69]
## ✏️ Description
마이페이지 API 연동 전 UI를 최종적으로 구현합니다.

## To-Do List
- [x] 팜클럽 히스토리 경로 변경
- [x] 탈퇴하기 바텀시트 구현
- [x] 푸시알림 토글 버튼 구현
