### ISSUE TITLE
[Feat] : 마이페이지 모든 API 연동

### ISSUE THREAD

**Issue by Ryeolee** [Mojacknong/Mojacknong_Android#70]
## ✏️ Description
마이페이지에 있는 모든 API 연동

## To-Do List
- [ ] 프로필 사진 API
- [ ] 탈퇴하기 API
- [ ] 채소 히스토리 API
- [ ] 팜클럭 히스토리 API
